name: VoidTeleport
version: 1.0.0
main: me.kevinnovak.voidteleport.VoidTeleport
author: KevinNovak
description: Teleport players out of the void!

commands:
    vtp:
        usage: /<command>
        description: List all VoidTeleport commands.
        aliases: [voidteleport]

permissions:
    voidteleport.command.setspawn:
        description: Set the worlds spawn to your location.
        default: op
    voidteleport.command.spawn:
        description: Teleport to the worlds spawn location.
        default: op
    voidteleport.command.random:
        description: Teleport to a random location in the world.
        default: op